default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_DBUSER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  pool: 5

development:
  <<: *default
  database: open_ai_development

test:
  <<: *default
  database: open_ai_test

production:
  <<: *default
  database: open_ai_production
  username: open_ai
  password: <%= ENV['OPEN_AI_DATABASE_PASSWORD'] %>
